### ISSUE TITLE
Support Nextjs + Stylable in a container

### ISSUE THREAD

**Issue by ItayTur** [wix/stylable#1781]
Hi, 

Following my last attempt to deploy nextJs + stylable with vercel - https://github.com/wix/stylable/issues/1710,
I'm now deploying the app using container and google cloud platform to host it.

I managed to run the app in a container with the styles working well,
The only issue is that the styles only apply when `NODE_ENV=development`.

if it's `NODE_ENV=production` the styles don't apply.

this are the scripts:

```
  "scripts": {
    "dev": "node server.js -p $PORT",
    "build": "next build",
    "start": "NODE_ENV=development node server.js -p $PORT"
  }
```

any idea how to combine  webpack in production env and apply the styles ?

all of the code can be found here - https://github.com/wix/stylable/issues/1710
if it's a burden that it's in another issue,  I'll copy/paste it here.

**Comment by tomrav** [comment]
Replying to show we're not ignoring this, I hope to have some progress to share very soon.

**Comment by barak007** [comment]
Assuming you use Stylable 4 try to use this plugin config.

```js

config.plugins.push(
  new StylableWebpackPlugin({
    filename: "static/css/stylable.css",
  })
);
```

You will still have and issue related to assets but we have a PR the should solve it. #1784

**Comment by ItayTur** [comment]
I don't have Stylable npm package in the project, it's not one of the dependencies.
I have the plugin `@stylable/webpack-plugin` version: `3.12.4`.
Looking in `package-lock.json`, all of the related stylable (e.g `@stylable/core`), are also version: `3.12.4`.

I tried adding this line to the plugin `filename: "static/css/stylable.[contenthash].css"` but it still didn't got the styles to apply in the container.

**next.config.js**

```
const { StylableWebpackPlugin } = require("@stylable/webpack-plugin");
const { attachHook } = require("@stylable/node");

attachHook();

module.exports = {
  webpack: (config) => {
    config.node = {
      fs: "empty",
    };

    safelyWalkJSON(config.module, insertStCssExclude(/\.st\.css$/));

    config.plugins.push(
      new StylableWebpackPlugin({
        includeDynamicModulesInCSS: false,
        filename: "static/css/stylable.[contenthash].css"
      })
    );

    return config;
  },
};

function insertStCssExclude(stRegex) {
  return (key, value) => {
    if (value && value.test) {
      if (value.test.toString().includes("css")) {
        if (value.exclude && Array.isArray(value.exclude)) {
          value.exclude.push(stRegex);
        } else if (value.exclude instanceof RegExp) {
          value.exclude = [value.exclude, stRegex];
        } else if (typeof value.exclude === "function") {
          value.exclude = [value.exclude, stRegex];
        } else if (value.exclude) {
          throw new Error("unknown exclude pattern: " + value.exclude);
        } else {
          value.exclude = [stRegex];
        }
      }
    }
  };
}

function safelyWalkJSON(obj, visitor, path = [], visited = new Set()) {
  for (var key in obj) {
    const currentPath = [...path, key];
    if (visited.has(obj[key])) {
      continue;
    } else {
      visited.add(obj[key]);
    }
    const res = visitor(key, obj[key], currentPath);
    if (res === false) {
      continue;
    }
    if (typeof obj[key] === "object") {
      safelyWalkJSON(obj[key], visitor, currentPath, visited;
    }
  }
}
```

**server.js**

```
// server.js
const { createServer } = require("http");
const { parse } = require("url");
const next = require("next");

const dev = process.env.NODE_ENV !== "production";
const app = next({ dev });
const handle = app.getRequestHandler();

require("@stylable/node").attachHook();

app.prepare().then(() => {
  createServer((req, res) => {
    const parsedUrl = parse(req.url, true);

    handle(req, res, parsedUrl);
  }).listen(process.env.PORT, (err) => {
    if (err) throw err;
    console.log("> Ready on http://localhost:" + " " + process.env.PORT);
  });
});
```

**Scripts**

```
"scripts": {
    "dev": "node server.js -p $PORT",
    "build": "next build",
    "start": "NODE_ENV=production node server.js -p $PORT"
  }
```

maybe it's related, when running the container in `prod env`, next asked me to run `next build` before. i did, build the image and run the container again, the app run with no styles. but the thing is that it didn't ask me to do it in the `dev env`.

**Comment by tomrav** [comment]
Could you by any chance try to upgrade to our latest version and follow the integration instructions from here: https://stylable.io/docs/getting-started/nextjs-integration ?

**Comment by ItayTur** [comment]
Hey Tom,
I installed stylable, upgrade the plugin to the latest version, followed the instructions, still no go.
I copy/paste the `next.config.js` example from the link, instead of my current `next.config.js`.
Now the build fails with this error:

```
#11 2.425 > Build error occurred
#11 2.427 TypeError: Cannot read property 'dependencies' of undefined
#11 2.427     at Object.getWebpackEntities (/app/node_modules/@stylable/webpack-plugin/dist/webpack-entities.js:10:110)
#11 2.427     at StylableWebpackPlugin.apply (/app/node_modules/@stylable/webpack-plugin/dist/plugin.js:55:44)
#11 2.427     at webpack (/app/node_modules/webpack/lib/webpack.js:51:13)
#11 2.427     at /app/node_modules/webpack/lib/webpack.js:36:39
#11 2.427     at Array.map (<anonymous>)
#11 2.427     at webpack (/app/node_modules/webpack/lib/webpack.js:36:24)
#11 2.427     at /app/node_modules/next/dist/build/compiler.js:4:172
#11 2.427     at new Promise (<anonymous>)
#11 2.427     at runCompiler (/app/node_modules/next/dist/build/compiler.js:4:106)
#11 2.427     at build (/app/node_modules/next/dist/build/index.js:13:348)
```

**Comment by barak007** [comment]
it seems that the webpack version is not correct. what `NextJS` version you use?

**Comment by ItayTur** [comment]
I use version 9.5.5

**Comment by tomrav** [comment]
Looks like [`v10.2.3`](https://github.com/vercel/next.js/releases/tag/v10.2.3) is the latest version, we've seen it working with versions `^10.2` and `@stylable` version `^4`.

Any chance you can try and upgrade your project?

**Comment by ItayTur** [comment]
I updated to `next latest:  10.2.3` and added `stylable: 5.4.11` still getting this error:
```
(node:20) UnhandledPromiseRejectionWarning: Error: Cannot find module 'webpack/lib/dependencies/NullDependency'
Require stack:
- /app/node_modules/@stylable/webpack-plugin/cjs/stylable-dependencies.js
- /app/node_modules/@stylable/webpack-plugin/cjs/stylable-bootstrap-module.js
- /app/node_modules/@stylable/webpack-plugin/cjs/stylable-webpack-plugin.js
- /app/node_modules/@stylable/webpack-plugin/cjs/index.js
- /app/next.config.js
- /app/node_modules/next/dist/next-server/server/config.js
- /app/node_modules/next/dist/server/next.js
- /app/server.js
```

**Comment by AviVahl** [comment]
`stylable@5.4.11` is a really old version and a deprecated package. use `@stylable/core` and `@stylable/webpack-plugin`.

Also, from the stack trace, it seems the version of `@stylable/webpack-plugin` being used is not the latest (I believe `stylable-dependencies.js` doesn't exist in recent versions). Please make sure the  latest `core` and `webpack-plugin` packages are on the latest versions as well.

**Comment by ItayTur** [comment]
ok there's some progress. I updated everything, and now I'm getting error regarding the build: 
`Error: Could not find a production build in the '/app/.next' directory.'` I'm checking it on my side.
still,
if I run `npm run build` locally, I get this error:
`./components/NavigationItem/NavigationItem.st.css
CssSyntaxError: C:\Users\Etai\OneDrive\Documents\GitHub\genie-action\src\NavigationItem.st.css:1:1: Unknown word`

I don't see reference to `server.js` in the stylable, but if I delete it and try to run with the default `nextjs scripts` it fails (even in dev-env)

the app should work without custom server ?

**Comment by AviVahl** [comment]
The server is most definitely not stylable's ;) It's probably NextJS's.
What's in `NavigationItem.st.css`? could it be that there is a syntax error in that file? Or is another loader (css-loader?) somehow processes .st.css files as well?

**Comment by AviVahl** [comment]
Btw, I just checked the instructions on my end. Everything seems to work on a fresh template:

- `npx create-next-app --typescript`
- press Enter to accept `my-app` as default app name
- `cd my-app`
- `yarn add @stylable/core @stylable/webpack-plugin --dev`
- create `next.config.js` with the contents from https://stylable.io/docs/getting-started/nextjs-integration/
- create `pages/test.st.css` containing `:global(body) { background-color: blue; }`
- add `import './test.st.css` to `pages/index.tsx`.

Background gets to be blue. It appears to work.

Not sure what's changed in the project you are testing. I suggest creating a working fresh copy of their template plus stylable and comparing where it different.

**Comment by ItayTur** [comment]
Running the app locally with stylable is working fine.
the issue is running the app in production mode in a docker container.
server  is an old solution: https://github.com/wix/stylable/issues/1212 , and yes it does work now without it locally.
but in the container, I still get an error about the build.
I created a new app from scratch and upload the repo: https://github.com/ItayTur/nextjs-stylable-prod-container
in the readme file there is the instructions to create an image and run a container.

**Comment by barak007** [comment]
I found the issue will be fix in the next Stylable release.

**Comment by tomrav** [comment]
We just released [v4.2.5](https://github.com/wix/stylable/releases/tag/v4.2.5), which should hopefully resolve your issue, please give it a try.

Re-opening until you confirm it works.
